services:
  - type: web
    name: imagetosvg-converter
    env: static
    buildCommand: echo "No build required"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
